// Generated by `npm run db:types` (or via the Supabase MCP `generate_typescript_types`).
// Do NOT edit by hand — regenerate after every migration.
// Convenience aliases at the bottom are project-specific.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          created_at: string
          display_name: string
          id: string
        }
        Insert: {
          created_at?: string
          display_name?: string
          id: string
        }
        Update: {
          created_at?: string
          display_name?: string
          id?: string
        }
        Relationships: []
      }
      bookings: {
        Row: {
          car_id: string | null
          car_label: string
          created_at: string
          customer_email: string | null
          customer_id: string | null
          customer_name: string
          customer_phone: string
          days: number
          destination: string | null
          id: string
          notes: string | null
          passengers: number | null
          pickup_date: string
          ref: string
          source: string
          status: Database["public"]["Enums"]["booking_status"]
          total_kwd: number
          updated_at: string
        }
        Insert: {
          car_id?: string | null
          car_label: string
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name: string
          customer_phone: string
          days: number
          destination?: string | null
          id?: string
          notes?: string | null
          passengers?: number | null
          pickup_date: string
          ref?: string
          source?: string
          status?: Database["public"]["Enums"]["booking_status"]
          total_kwd: number
          updated_at?: string
        }
        Update: {
          car_id?: string | null
          car_label?: string
          created_at?: string
          customer_email?: string | null
          customer_id?: string | null
          customer_name?: string
          customer_phone?: string
          days?: number
          destination?: string | null
          id?: string
          notes?: string | null
          passengers?: number | null
          pickup_date?: string
          ref?: string
          source?: string
          status?: Database["public"]["Enums"]["booking_status"]
          total_kwd?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookings_car_id_fkey"
            columns: ["car_id"]
            isOneToOne: false
            referencedRelation: "cars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_car_id_fkey"
            columns: ["car_id"]
            isOneToOne: false
            referencedRelation: "v_top_cars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      cars: {
        Row: {
          available: boolean
          created_at: string
          engine: string
          featured: boolean
          features: Json
          id: string
          image_url: string
          model: string
          name_ar: string
          name_en: string
          price_per_day: number
          rentals_count: number
          seats: number
          slug: string
          transmission: string
          type: Database["public"]["Enums"]["car_type"]
          updated_at: string
          year: number
        }
        Insert: {
          available?: boolean
          created_at?: string
          engine: string
          featured?: boolean
          features?: Json
          id?: string
          image_url: string
          model: string
          name_ar: string
          name_en: string
          price_per_day: number
          rentals_count?: number
          seats: number
          slug: string
          transmission: string
          type: Database["public"]["Enums"]["car_type"]
          updated_at?: string
          year: number
        }
        Update: {
          available?: boolean
          created_at?: string
          engine?: string
          featured?: boolean
          features?: Json
          id?: string
          image_url?: string
          model?: string
          name_ar?: string
          name_en?: string
          price_per_day?: number
          rentals_count?: number
          seats?: number
          slug?: string
          transmission?: string
          type?: Database["public"]["Enums"]["car_type"]
          updated_at?: string
          year?: number
        }
        Relationships: []
      }
      customers: {
        Row: {
          created_at: string
          email: string | null
          id: string
          name: string
          notes: string | null
          phone: string
          tier: Database["public"]["Enums"]["customer_tier"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          name: string
          notes?: string | null
          phone: string
          tier?: Database["public"]["Enums"]["customer_tier"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          name?: string
          notes?: string | null
          phone?: string
          tier?: Database["public"]["Enums"]["customer_tier"]
          updated_at?: string
        }
        Relationships: []
      }
      testimonials: {
        Row: {
          created_at: string
          customer_name: string
          id: string
          published: boolean
          rating: number
          text: string
        }
        Insert: {
          created_at?: string
          customer_name: string
          id?: string
          published?: boolean
          rating?: number
          text: string
        }
        Update: {
          created_at?: string
          customer_name?: string
          id?: string
          published?: boolean
          rating?: number
          text?: string
        }
        Relationships: []
      }
    }
    Views: {
      v_kpis: {
        Row: {
          active_bookings: number | null
          cars_available: number | null
          cars_total: number | null
          new_customers: number | null
          revenue_month: number | null
        }
        Relationships: []
      }
      v_revenue_monthly: {
        Row: {
          bookings: number | null
          revenue: number | null
          ym: string | null
        }
        Relationships: []
      }
      v_top_cars: {
        Row: {
          id: string | null
          image_url: string | null
          model: string | null
          name_ar: string | null
          rentals: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      is_admin: { Args: Record<string, never>; Returns: boolean }
    }
    Enums: {
      booking_status: "pending" | "confirmed" | "completed" | "cancelled"
      car_type: "luxury" | "suv" | "sports"
      customer_tier: "bronze" | "silver" | "gold"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      booking_status: ["pending", "confirmed", "completed", "cancelled"],
      car_type: ["luxury", "suv", "sports"],
      customer_tier: ["bronze", "silver", "gold"],
    },
  },
} as const

// ----- Project-specific convenience aliases (kept stable for app code) -----
export type Car         = Database["public"]["Tables"]["cars"]["Row"]
export type Customer    = Database["public"]["Tables"]["customers"]["Row"]
export type Booking     = Database["public"]["Tables"]["bookings"]["Row"]
export type Testimonial = Database["public"]["Tables"]["testimonials"]["Row"]

export type CarType        = Database["public"]["Enums"]["car_type"]
export type BookingStatus  = Database["public"]["Enums"]["booking_status"]
export type CustomerTier   = Database["public"]["Enums"]["customer_tier"]
